### ISSUE TITLE
Add accurate return typing to uploadAsset() in main.ts

### ISSUE THREAD

**Issue by Andrew-Kulpa** [Andrew-Kulpa/create-release#3]
#### Description
The uploadAsset() function does not have a return type specified.

#### Files
`./src/main/main.ts`

#### Tasks

- [ ] Add an accurate return type to uploadAsset()

**Comment by mcrosby114** [comment]
I'll take a stab!

**Comment by pedro-mass** [comment]
How deep do you want the typing?
Doesn't seem like anything is being down with the return other than awaiting, so it can be as simple as `: Promise<any>`

If deeper typing is desired, looks like it'll be quite verbose (and potentially increase the bundle size?)

Here's the type definition file: https://raw.githubusercontent.com/octokit/rest.js/master/index.d.ts

Search for `uploadReleaseAsset: {` to find the return type.

**Comment by mcrosby114** [comment]
Bummer @pedro-mass, I was going to take this one 😢
