### ISSUE TITLE
Authorship, licensing and core principle

### ISSUE THREAD

**Issue by majkrzak** [Andrew-Kulpa/create-release#9]
Hello,

I've noticed that you decided to develop my GitHub release management action. I'm glad about it, but I'm a bit irritated due to the fact that you made it in the form of plagiarism.

Anyway, I hope we will quickly solve the issue together. One solution might be to **add original authorship information to the readme and action description** second is to **contribute directly to my repo**.

What I'm mostly disappointed with, is that you destroyed main principle of this repo which was implemented in very first lines of the original code:

```js
require('child_process')
  .execSync(
    'npm install @actions/core @actions/github',
    { cwd: __dirname }
  );
```

The point was to avid committing `node_modules` and other "non source code stuff" to the repository.

**Comment by Niko9911** [comment]
I'm just following this :eyes:

**Comment by Andrew-Kulpa** [comment]
Hello majkrzak,

I apologize for any misgivings. Yes, its a fork from your initial version, so the base code will be similar. I have removed licensing details from my fork and added attribution to you in the readme and action.yml as requested. 

If you dislike my removal of that code you referenced above, then you are welcome not to pull in new code changes. I disagreed with its inclusion and removed it in this fork. As this was an entire overhaul and extension of your version with a great difference in core principles, this may be for the best.

**Comment by majkrzak** [comment]
Hi, 

About the authorship, I'm happy that you noticed your mistake. 
https://github.com/Andrew-Kulpa/create-release/blob/301f328cf1b3ec753c8061122ba65ce83befd415/package.json#L14 You should keep yourself as the author here and just mention my initial work in the description. It's fine to just mention my work in the description.

About the "core concept" I will describe it and add as a pull request later in the evening.

I'm also going to watch this repo and give you some feedback, cause it looks that you are not too familiar with what you are doing.

**Comment by Andrew-Kulpa** [comment]
Understood. After some research earlier I did update the `package.json` accordingly as it is essentially a new package (which I figure is what you're hinting at). Authorship and attribution is not my finest topic, so I apologize for any misunderstandings there :smiley:

**Comment by majkrzak** [comment]
https://github.com/Andrew-Kulpa/create-release/blob/master/README.md#original-authorship
Please drop this section, it is ridiculous

**Comment by MarshallJamesRaynor** [comment]
stai attento.

**Comment by Andrew-Kulpa** [comment]
Just crossing t's and dotting i's man. Since you don't feel it necessary I reverted it.
